Feature/tests
vtex-apps/supply-lots pull request #4
Opened 2021-07-02 12:12 UTC by anamaiabap

Testes + Rodada de correções do codigo

2021-07-02 12:37 UTC, wagnerlduarte commented
Nos casos como esse, que o desenvolvimento feito na branch `feature/changeStyle` foi aproveitado para criar a branch `feature/tests`, ao abrir PR o ideal é que seja usado o stacked pull requests, para melhorar a visibilidade do diff e não ter que revisar tudo que estava no primeiro PR novamente.

Nesse caso, esse PR (https://github.com/vtex-apps/supply-lots/pull/4) deve apontar para a branch que já existe um PR aberto (https://github.com/vtex-apps/supply-lots/pull/3).

O apontamento desse PR deve ser para a branch `feature/changeStyle`. Dessa forma o diff mostrará somente o que mudou entre `feature/tests` e `feature/changeStyle`, e não entre `feature/tests` e `master` como está agora.
![image](https://user-images.githubusercontent.com/17439470/124275441-e73a7c80-db18-11eb-8a31-b7ec6c1dc940.png)



Esse link exemplifica o processo: https://timothyandrew.dev/blog/git-stack/

2021-07-02 12:37 UTC, wagnerlduarte requested changes
Nos casos como esse, que o desenvolvimento feito na branch `feature/changeStyle` foi aproveitado para criar a branch `feature/tests`, ao abrir PR o ideal é que seja usado o stacked pull requests, para melhorar a visibilidade do diff e não ter que revisar tudo que estava no primeiro PR novamente.

Nesse caso, esse PR (https://github.com/vtex-apps/supply-lots/pull/4) deve apontar para a branch que já existe um PR aberto (https://github.com/vtex-apps/supply-lots/pull/3).

O apontamento desse PR deve ser para a branch `feature/changeStyle`. Dessa forma o diff mostrará somente o que mudou entre `feature/tests` e `feature/changeStyle`, e não entre `feature/tests` e `master` como está agora.
![image](https://user-images.githubusercontent.com/17439470/124275441-e73a7c80-db18-11eb-8a31-b7ec6c1dc940.png)



Esse link exemplifica o processo: https://timothyandrew.dev/blog/git-stack/

2021-07-05 14:48 UTC, wagnerlduarte commented on react/components/Modal/add.tsx
> +import { injectIntl, useIntl } from 'react-intl'
Se passou a usar o `useIntl` não precisa mais do `injectIntl`

2021-07-05 14:48 UTC, wagnerlduarte commented on package.json
> +    "react-intl": "3",
Houve algum problema na versão 5 do `react-intl` para ter feito o downgrade para a versão 3?

2021-07-05 14:48 UTC, wagnerlduarte commented on react/components/Provider/Warehouse.tsx
> +    if (dataListSupplyLots?.listSupplyLots?.length > 9) {
O que significa o número 9 nessa condição?
Uma boa prática é criar uma const com o nome declarativo informando o significado do valor que usou para comparar.
Ex.: `const SUPPLY_LOTS_LIMIT_TO_SHOW = 9`

Obs.: não levar em consideração o nome que eu dei para a `const` do exemplo, foi mais uma sugestão da aplicação da boa prática, mesmo 😄

2021-07-05 14:48 UTC, wagnerlduarte commented on react/components/Provider/Warehouse.tsx
> +    }
Sugestão de alteração para melhorar a legibilidade da condição, se achar quer faz sentido:

```suggestion
    if (dataListSupplyLots?.listSupplyLots?.length > 9 && !limit) {
      setLimit(true)
    } else if (limit) {
      setLimit(false)
    }
```

2021-07-06 13:03 UTC, anamaiabap commented on package.json
> +    "react-intl": "3",
na verdade foi um teste pois não estava reconhecendo a função do useIntl, mas foi outra coisa e esqueci de voltar a versão
Obrigada pelo aviso :)

2021-07-06 13:07 UTC, anamaiabap commented on react/components/Provider/Warehouse.tsx
> +    if (dataListSupplyLots?.listSupplyLots?.length > 9) {
Indica até quantos supply lots podem ser adicionados!
Gostei muita da dica, irei usar essa prática a partir de agora :)

2021-07-06 13:09 UTC, anamaiabap commented on react/components/Provider/Warehouse.tsx
> +    }
Eu tinha feito essa condição assim antes, mas acontece que dependendo do caso ela não funciona como deveria, então fiz essa alteração que passou a funcionar corretamente.
Se quiser posso te explicar melhor no slack!

2021-07-07 11:45 UTC, wagnerlduarte approved these changes

2021-07-14 16:43 UTC, merged